### PR TITLE
defcustom `org-roam-capture-templates`

### PR DESCRIPTION
**Pull request by myshevchuk**
Declare `org-roam-capture-templates` with `defcustom` and update the
docstring

See #922

###### Motivation for this change

`org-roam-capture-templates` is a user variable and should be accessible from the Customize interface.

### CODE REVIEW

**Comment by zaeph** [comment]
Thanks.  I'll review this later today.

**Comment by myshevchuk** [comment]
I'll also do the same for `org-roam-capture-ref-templates` and `org-roam-capture-immediate-template`, so don't merge this yet. By the way, what was the rationale behind two additional templates variables? I didn't follow Org-roam closely for a while.

**Comment by zaeph** [comment]
> By the way, what was the rationale behind two additional templates variables?

Users where bothered by the inability to nest `org-capture` sessions, and we've proposed those commands as an alternative which allowed to return directly from an `org-capture` session at the cost of being able to cancel it with `C-c C-k`.  It's a temporary fix which will have to do until we reconsider whether we actually need `org-capture`.

This is not to say that your work would be useless, by the way.  Presumably, we'd only be changing the plumbing, not the front-end for those templates, and it would be transparent for the users.

**Comment by zaeph** [comment]
Thanks!

**Comment by zaeph** [comment]
Ah, damn it, just remembered that you wanted to hold off until you'd addressed the other variables.  Sorry!

**Pull request merged**
