### PR TITLE
(internal): use regexp-search for fuzzy link replacement

### PR DESCRIPTION
**Pull request by jethrokuan**
This should improve responsiveness on large files

### CODE REVIEW

**Comment by TimQuelch** [comment]
How does this interact with places where links cannot appear such as within source blocks? 

If I have,

    #+begin_src python
    a = [['some text']]
    #+end_src

will this change interpret this as a fuzzy link and attempt to replace this?

The reason I ask is I'm having trouble saving a note with a large number of source blocks with brackets everywhere and it is just hanging on save. I haven't done significant debugging yet but I thought that this might be the issue.

If this is the issue I think it would apply to #1066.

**Comment by TimQuelch** [comment]
I just reverted to f6bf9d94019547436f565156bf7dc12f414cfa86 and it fixed the issue i'm having, so I do think it is these changes to regexp which is the problem. I might have time to do a full bisect later.

**Comment by jethrokuan** [comment]
yes, this is also the cause of #1069, looks like replacing fuzzy link behaviour backfired a little.

**Comment by jethrokuan** [comment]
The real offender is the unneeded `(goto-char (match-beginning 0))` which will cause the link replacement to fail when it does not find a match, but I fixed it all in one go in #1070 .

**Pull request merged**
