### PR TITLE
(fix) Capture template initial text

### LINKED ISSUE #1433: Copy selection from browser when using it with org-protocol
What would be the org-roam-capture-templates / bookmark config when wanting to include selected text in the capture frame? Thanks.

### PR DESCRIPTION
**Pull request by seanfarley**
###### Motivation for this change

Mostly to fix #1433 but also discuss the format of the file name (slug).

### CODE REVIEW

**Comment by seanfarley** [comment]
Follow-up question: is there a technical reason that `%i` isn't included in the default `org-roam-capture-ref-templates`?

**Comment by jethrokuan** [comment]
> Follow-up question: is there a technical reason that %i isn't included in the default org-roam-capture-ref-templates?

No, that's a mistake. Although `%i` could really be replaced with `{body}` in the ref template.

> Discuss the format of the file name (slug)

It's probably not a good idea to change the defaults at this time.

**Comment by seanfarley** [comment]
> > Follow-up question: is there a technical reason that %i isn't included in the default org-roam-capture-ref-templates?
> 
> No, that's a mistake. Although `%i` could really be replaced with `{body}` in the ref template.

But wouldn't that mean `{body}` is _always_ required? e.g. I wouldn't be able to `org-roam-capture` a webpage without selecting text
 
> > Discuss the format of the file name (slug)
> 
> It's probably not a good idea to change the defaults at this time.

That's too bad.

I'll update the PR to drop that change.

**Review by jethrokuan — APPROVED** [review]

**Comment by seanfarley** [comment]
Thanks!

**Pull request merged**
