### PR TITLE
(feat): Add support for emacs-sqlite3 #682

### PR DESCRIPTION
**Pull request by nobiot**
It would be great if you could consider and review this.
Happy to have constructive critiques, or accept decline if that is the conclusion of the contributors.

At the moment, I have not removed my plugin to work with markdown files -- this is my normal usage and I have only one or two test `.org` files. I understand if this might be considered interfering with proper testing. It would be great if other Windows users, Linux and macOS users to test.

###### Motivation for this change
Motivation: issue #682 

For Windows users, requiring emacs-sqlite is an entry barrier as
there is no out-of-the-box way to compile it when launching
org-roam for the first time.

Add customizing variable `org-roam-db-use-sqlite3`.
Set it non-nil tells org-roam to use emacs-sqlite3 instead of
the default emacs-sqlite.

####### Some test results on my Windows 10 machine
As this is critical to existing users, I tried to focus more on regression tests. 
Regression on Linux or macOS is not done; I don't have access to them.

For each case, I manually deleted `org-roam.db` before starting.

## 1. Initial condition
- Removed compiled `emacsql-sqlite.exe`
- Set `org-roam-db-use-sqlite3` to `nil`
- Installed `emacsql-sqlite3` package
- Result as expected
image

## 2. Emacsql-sqlite3 enabled
- Removed compiled `emacsql-sqlite.exe`
- Set `org-roam-db-use-sqlite3` to `t`
- Installed `emacsql-sqlite3` package
- Result as expected (with the sqlite3 specific message from the update)
image

## 3. Emacsql-sqlite3 disabled, standard emacsql-sqlite used
- Compiled `emacsql-sqlite.exe`
- Set `org-roam-db-use-sqlite3` to `nil`
- Installed `emacsql-sqlite3` package
- Result as expected
image

## 4. Emacsql-sqlite3 uninstalled, standard emacsql-sqlite used
- Compiled `emacsql-sqlite.exe`
- Set `org-roam-db-use-sqlite3` to `nil`
- Purged `emacsql-sqlite3` package 
- Result as expected
image

### CODE REVIEW

**Comment by jethrokuan** [comment]
I looked through `emacsql-sqlite3`'s code and I don't see it doing anything much different from the original `emacsql-sqlite` code, except that it uses `(executable-find "sqlite3")` as the binary. This is also possible with `emacsql-sqlite`: instead of using the default compiled binary, you can point to your installed binary.

```
(use-package emacsql-sqlite
  :custom (emacsql-sqlite-executable-path (executable-find "sqlite3"))

(use-package org-roam...)
```

Can you confirm that simply setting the binary path does not work? Would prefer not to pull in a new package.

**Comment by nobiot** [comment]
@jethrokuan, tried the variable as you suggested. 

Negative.
Do you think `emacsql-sqlite-executable-path` could work with `sqlite3.exe`, instead of `emacs-sqlite.exe` ?
Do you think it's worth trying to see if I can run `sqlite3` from within Emacs?
See detail below. 

I also tried this below, with `.exe` added (this seems to be the way Emacs on Windows), with the same negative result.
```
(use-package emacsql-sqlite
  :custom (emacsql-sqlite-executable-path (executable-find "sqlite3.exe")))
```

The error message you get in the end is:
`Query timeout error: "Query timed out", 30`.

This is probably because it takes virtually forever for `sqlite3.exe` command to return when run from within Emacs's `shell` or `eshell` (both tried).

I can run `sqlite3` with no problem directly from within `PowerShell` or `cmd`.

Regardless of the issue of `sqlite3` taking forever to return, though...

See this documentation below. Notice the docstring "this is not the sqlite3"...
image

Both variables shown are set by the customization.

In addition, looking at `defvar`, `emacsql-sqlite-executable-path` is for `emacsql-sqlite.exe`, not for `sqlite3.exe`.
```
(defvar emacsql-sqlite-executable-path
  (if (memq system-type '(windows-nt cygwin ms-dos))
      "sqlite/emacsql-sqlite.exe"
    "sqlite/emacsql-sqlite")
  "Relative path to emacsql executable.")
```
`emacs-sqlite.exe` is the one that needs to be compiled from the source.

What do you think?
Do you think it's worth trying to see if I can run `sqlite3` from within Emacs?

**Comment by nobiot** [comment]
My bad. I will correct my statement about "sqlite3 takes forever" in `shell` and `eshell` within Emacs.
I just read [this](http://sqlite.1065341.n5.nabble.com/sqlite-in-a-shell-td5985.html).

I tried `sqlite3` in both Emacs shells, followed by `.help`. See the screen excerpts below.
So... `sqlite3.exe` is running.

I think `sqlite3.exe` is not meant for `emacsql-sqlite-executable-path`, then?

image
**Figure 1.** eshell

image

**Figure 2.** shell

**Comment by notuntoward** [comment]
@nobiot and @jethrokuan, in #682, I also found that just pointing to the sqlite binary doesn't work on Windows.

**Comment by jethrokuan** [comment]
Thanks for confirming that just changing the binary path doesn't work.

> Since sqlite3 exists on Windows, Linux and MacOS, I wonder if the simplest solution wouldn't be to just use sqlite3 for all platforms?

Yes, I think that would be the ideal. Let me check if `emacsql-sqlite3` works out of the box on my machine.

**Comment by jethrokuan** [comment]
Superceded by #701

**Pull request closed without merging**
