### PR TITLE
(internal): use emacsql-sqlite3 everywhere

### PR DESCRIPTION
**Pull request by jethrokuan**
###### Motivation for this change

Emacsql-sqlite3 seems to work better for Windows, and has no effect for Linux users.

This is to address #682 .

### CODE REVIEW

**Comment by jethrokuan** [comment]
@nobiot @notuntoward appreciate if you could give this branch a try. Seems to work for me, and if it works on Windows I'll have it merged.

**Comment by notuntoward** [comment]
Thanks for the change -- #701 works for me on Windows.

But I should say that, since I haven't seriously used org-roam yet, my tests were on a small number of toy org-roam notes.

**Comment by nobiot** [comment]
Thank you. Works for me too.
My test condition and procedure below. I have 113 notes in my `org-roam-directory`...
All manual, and actual test in Step 6 is all casual and sporadic, but should include majority of operation I do within `org-roam` (apart from writing notes).  I don't use graph, or tags at the moment. 

Just one note for the last test case (with an external editor):
I got the Query timeout error, but the title and backlink were both created OK. No issue with `org-roam` after the initial start (i.e. `org-roam-db-build-cache` took time but worked fine).

> (org-roam) files: 1, links: 1, tags: 0, titles: 1, refs: 0, deleted: 0
> Query timeout error: "Query timed out", 30

I have this from time to time even with `emacsql-sqlite` so for me it's not related to change to `sqlite3`. 

## Condition
- Emacs: GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29 (via `org-roam-diagnostics`)

- SQLite version 3.32.0 2020-05-22 17:46:16 (via `sqlite3` command on PowerShell)


## Procedure
1. Check `org-roam` works before `fix/sqlite3` branch

2. Remove emacsql-sqlite.exe manually

3. Check emacsql-sqlite aborts 
   Compiling EmacSQL SQLite binary ...
emacsql-sqlite-ensure-binary: No EmacSQL SQLite binary available, aborting

4. PowerShell, `sqlite3` works.

```
> sqlite3
SQLite version 3.32.0 2020-05-22 17:46:16
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .help
.archive ...             Manage SQL archives
```

5. Pull, checkout `fix/sqlite3` branch. Ensure the code is where it is supposted to be, restart Emacs

6. Test.
  - Title change.
  - Create/delete a new backlink.
  - Create/delete a new cite links.
  - Check `C-c n i` (`org-roam-insert`)
  - Check alias works for `org-roam-insert`
 - Quite Emacs, create a note in an external editor, launch Emacs and `org-roam` to see if a backlink are created from the newly created file

**Comment by jethrokuan** [comment]
Great, thanks for checking!

**Pull request merged**
