### PR TITLE
Add prefill-current argument to org-roam-insert

### PR DESCRIPTION
**Pull request by zaeph**
This PR modifies `org-roam-insert` to accept a new optional, boolean argument, `prefill-current`.  When it is non-nil, `org-roam-insert` prefills the completion template with the title of the current entry.  It's useful for quickly creating notes from a topic card.

Here's a screencast:
output-2020-04-15-08:39:39

Note that this is something that can be easily expanded.  For instance, I'd like to create a command to create a new version of the current note.  For example, if I'm on the note 'Metaphor', and I don't agree with what I've written anymore, I could run a command and have it automatically create a `Metaphor v2` note.  The command would also check the current version-number and increment it for further versions.

How do you like this?

### CODE REVIEW

**Comment by Zaeph** [comment]
> Note that this something that can be easily expanded. For instance, I'd like to create a command to create a new version of the current note. For example, if I'm on the note 'Metaphor', and I don't agree with what I've written anymore, I could run a command and have it automatically create a `Metaphor v2` note. The command would also check the current version-number and increment it for further versions.

I think this would be best done by changing `PREFILL-CURRENT` to `PREFILL-FN`, which would be the name of a function who’d take one argument: the title of the current entry.  That way, we could do plenty of neat stuff.

**Comment by Zaeph** [comment]
> I think this would be best done by changing `PREFILL-CURRENT` to `PREFILL-FN`, which would be the name of a function who’d take one argument: the title of the current entry. That way, we could do plenty of neat stuff.

I went ahead and did it in 7997e3d.  Instead of taking one argument, though, the functions take two: the title of the current note, and the content of the region if it is active.

**Comment by asymmetric** [comment]
When is this useful in practice? i.e. what could come after `Metaphor: `?

**Comment by Zaeph** [comment]
> When is this useful in practice? i.e. what could come after `Metaphor: `?

You could have:
- `Metaphor: Comparison with simile`
- `Metaphor: Cognitive dimension`
- `Metaphor: Uses in rhetorics`

Those aren't *atomic* notes, but notes which aim to relate `Metaphor` to other notes/topic whilst keeping `Metaphor` as a soft-parent.

**Comment by asymmetric** [comment]
As I mentioned in #222 (not that my opinion matters that much tho! :smile: ), I think notions of parenting should not be part of org-roam, due to the inherent fragility of the concept of a "hierarchy of ideas".

In your examples, I guess I would simply keep the notes in one file, but you could obviously also split them up and link them back to a `Metaphor` note.

**Comment by asymmetric** [comment]
I wonder if [this](https://github.com/jethrokuan/org-roam/issues/317) issue (not implemented yet) could also work in your direction.

**Comment by Zaeph** [comment]
> As I mentioned in #222 (not that my opinion matters that much tho! smile ), I think notions of parenting should not be part of org-roam, due to the inherent fragility of the concept of a "hierarchy of ideas".

I agree with you, and this is echoed in Ahrens (2017):

> The quicker we get from the index to the concrete notes, the quicker we move our attention from mentally preconceived ideas towards the fact-rich level of interconnected content, where we can conduct a fact-based dialogue with the slip-box.

So, an index, and that’s it.  However, a point is also made about the importance of *rewriting* notes:

> What we regard as being relevant for a topic and how we structure it **will change over time**. This change might lead to another note with a different, more adequate topic structure, which then can be seen as a comment on the previous note. Thankfully, it won’t make all the other notes redundant. As mentioned before: **All we have to do is to change the entry in the index to this new note and/or indicate on the old note that we now consider a new structure more fitting**. [emphasis added]

So, in that regard, the PR would provides the facility to support those types of notes which have a *meta*-link to the previous entry.

To come back to the idea of prepending the title of new entries with something like `Metaphor: `, I’ve mentioned the idea of *soft-parent*.  When you think about the way Luhmann incorporated the method, he only branched off onto another slash (i.e. from `12/a` to `12/a/1`), it was because he wanted to continue in a similar direction, but there was already a note after it.  That’s why I say that the note thus created is a *soft-child* of the previous one because its existence was warranted *as a result* of its *soft-parent*.  Since we’re not bound to paper limitations with `org-roam`, you can also think of creation-times and modification-times as *softly* linking notes.  They shouldn’t take precedence on the manual associations we made between notes, however far-reaching they may be, but I think there is value in having them.

> In your examples, I guess I would simply keep the notes in one file, but you could obviously also split them up and link them back to a `Metaphor` note.

See, I’d tried that in my first notes, and I ended up with gargantuan notes which weren’t all that easy to browse.  But I think you’ve brought up a valuable issue, and I’d love to hear the opinions of others on this.

> I wonder if [this](https://github.com/jethrokuan/org-roam/issues/317) issue (not implemented yet) could also work in your direction.

Thanks for pointing me to it.  Indeed, it seems related, but it also looks like it hasn’t been robustly implemented yet.  I’ll have a deeper look when I get the chance.

### References
<div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Ahrens, Sönke. <i>How to Take Smart Notes: One Simple Technique to Boost Writing, Learning and Thinking for Students, Academics and Nonfiction Book Writers</i>, 2017.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-1-5428-6650-7&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=How%20to%20Take%20Smart%20Notes%3A%20One%20Simple%20Technique%20to%20Boost%20Writing%2C%20Learning%20and%20Thinking%20for%20Students%2C%20Academics%20and%20Nonfiction%20Book%20Writers&amp;rft.aufirst=S%C3%B6nke&amp;rft.aulast=Ahrens&amp;rft.au=S%C3%B6nke%20Ahrens&amp;rft.date=2017&amp;rft.isbn=978-1-5428-6650-7&amp;rft.language=English"></span>
</div>

**Pull request closed without merging**
