### PR TITLE
(feat): split org-roam-buffer-toggle into -activate and -deactivate

### PR DESCRIPTION
**Pull request by langston-barrett**
###### Motivation for this change
I want to create a hook for activating this buffer when I enter an org file and deactivating it when I leave.

### CODE REVIEW

**Comment by zaeph** [comment]
Doom did something like that.  You should look up how they did it on their end.

**Comment by langston-barrett** [comment]
> Doom did something like that. You should look up how they did it on their end.

Here's that code: https://github.com/hlissner/doom-emacs/blob/da3c1cb78dd806cd45f8c8520ebaf8db5c031802/modules/lang/org/contrib/roam.el#L53

It's not that different from what's in this PR. In fact, the call to the internal function `(org-roam-buffer--get-create)` in that code could instead be a call to `(org-roam-buffer-activate)`, which this PR exposes as part of the "public API".

**Comment by zaeph** [comment]
Sorry, hadn't realised that it was a PR.  I'll have a look tomorrow, but I'd like to make this behavior optional and off by default.  We'll need to think about this for the revamp.

**Comment by langston-barrett** [comment]
@zaeph No worries! Also, just a note that this is fully backwards compatible, the behavior of `org-roam-buffer-toggle` stays exactly the same.

**Comment by zaeph** [comment]
I don't see any problem with splitting the toggle into two functions.  Thanks!

**Pull request merged**
