### PR TITLE
(fix): don't print no citelinks if org-ref is not present

### PR DESCRIPTION
**Pull request by jethrokuan**
###### Motivation for this change

Change confusing behaviour where org-roam buffer prints "no citelinks"
even when org-ref is not present.

### CODE REVIEW

**Comment by TimQuelch** [comment]
Might it be worth not printing cite links at all of no `ROAM_KEY` is present?

**Comment by jethrokuan** [comment]
oops @TimQuelch that makes sense too.

**Comment by TimQuelch** [comment]
I saw the merge happen right as I was typing it out :o

**Comment by jethrokuan** [comment]
Done in #717

**Pull request merged**
