### PR TITLE
Exclude backup files from renaming advice

### PR DESCRIPTION
**Pull request by mxco86**
Exclude backup files from triggering the file/link renaming advice

### CODE REVIEW

**Comment by zaeph** [comment]
Closes #905.

**Comment by npalermo10** [comment]
Yeah the update fixes it. Thanks!

**Comment by zaeph** [comment]
It hasn't fixed it for everyone apparently, though, cf #909.

**Comment by zaeph** [comment]
Two persons have confirmed that this fix works for them, and I don't think this would cause problem elsewhere.  I'll investigate some more later, but it's not a blocker.

Merging.

**Comment by zaeph** [comment]
Oh, and thank you!

**Pull request merged**
