### PR TITLE
Insert links optimization: require org-ref once

### PR DESCRIPTION
**Pull request by hugoArregui**
###### Motivation for this change

A big file with a lot of links take a while to sync, even when its structure it's pretty simple (no headings), I discover one of the reasons for this is every time we insert a link we require org-ref. This is specially annoying if you sync in save.

By creating a special insert-links function, instead of mapping links and apply a generic set of functions, I'm able to only require org-ref once. In my local env the mapping/insertion was taking around 2.32 secs and now it takes 0.83 secs.

### CODE REVIEW

**Comment by jethrokuan** [comment]
If the issue is really with `(require 'org-ref)` being slow, it's possible to move the require out of the block to the top level update function, leaving the `boundp` check there (which should be relatively fast), which would leave most of the modularized code in place.

It might also make sense to have a macro `(org-roam-with-requires @body)` which does all the requiring so the body wouldn't need to do so.

**Comment by hugoArregui** [comment]
@jethrokuan I'm not quite sure to understand your suggestion, do you mean doing something like 

```lisp
(let ((org-ref-enabled ...))
  (org-roam-db-map-links
             (list (lambda (link) (org-roam-db-insert-link org-ref-enabled link)))
```

in org-roam-db-update-file?

**Comment by jethrokuan** [comment]
@hugoArregui I meant moving `(require 'org-ref nil 'noerror)` from `org-roam-db-insert-link` to `org-roam-db-update-file` and removing it from `org-roam-db-insert-link`. `boundp` checks should be much and take negligible time.

**Comment by hugoArregui** [comment]
@jethrokuan sorry but I don't quite follow, we still want to run `org-roam-db-insert-link` if org ref is not available, so I don't quite know how we can remove it from `org-roam-db-insert-link`. Very sorry if I'm missing something obvious.

**Comment by jethrokuan** [comment]
All the slowness has been addressed appropriately I think, with #1944 and #1946, closed in favour of these two PRs.

**Pull request closed without merging**
