### PR TITLE
Use hash-table-keys function to extract completion titles for ido

### PR DESCRIPTION
**Pull request by p4v4n**
Bug Fix : https://github.com/org-roam/org-roam/issues/636

### CODE REVIEW

**Comment by zaeph** [comment]
Thanks for the PR, checking it out.

**Comment by zaeph** [comment]
LGTM, and it works on my end.

**Comment by zaeph** [comment]
Thanks!

**Comment by pprevos** [comment]
Thanks for working on the fix. The error has changed now: 

`org-roam-find-file: Wrong type argument: characterp, \,`
`org-roam-insert: Wrong type argument: characterp, \, `

**Comment by progfolio** [comment]
Can you please `M-x toggle-debug-on-error` and paste the backtrace from the debugger buffer?

**Comment by pprevos** [comment]
`Debugger entered--Lisp error: (wrong-type-argument characterp \,)
  org-roam--get-title-path-completions()
  org-roam-find-file()
  funcall-interactively(org-roam-find-file)
  call-interactively(org-roam-find-file nil nil)
  command-execute(org-roam-find-file)`

**Comment by zaeph** [comment]
Someone had a similar problem on Slack, and it was due to commas being used as separators `#+ROAM_TAGS`:
```org
Good:
#+ROAM_KEY: "foo" "bar

Bad:
#+ROAM_KEY: "foo", "bar
```

Can you confirm that this is a problem in your files?

**Comment by pprevos** [comment]
Thanks Zeaph, my bad. I indeed had a comma between tags. I'm happy now - back to building my network of old notes.

**Pull request merged**
