### PR TITLE
(feat): org-roam-find-file-function customization

### PR DESCRIPTION
**Pull request by progfolio**
Allow users to specify a function for finding files in various commands.
Can be let-bound to define new commands that suit user preferences.

See: #790

### CODE REVIEW

**Comment by progfolio** [comment]
Note this does not add any extra `...other-window` commands as #790 does and does not address the case of `org-roam-switch-to-buffer`.

**Comment by zaeph** [comment]
> and does not address the case of `org-roam-switch-to-buffer`.

I'll think about this tomorrow.

**Comment by jethrokuan** [comment]
Feel free to rebase and merge here.

**Comment by zaeph** [comment]
I will.  Just finishing up with the notifications and I'll get on it.

**Comment by zaeph** [comment]
Yeah, sorry, I haven't had time to get back to this one.  I'll review this later.

**Pull request merged**
