### PR TITLE
(feat): add org-roam-find-file-immediate

### PR DESCRIPTION
**Pull request by jethrokuan**
##### Motivation for Change

Adds `org-roam-find-file-immediate`. Ref #852.

### CODE REVIEW

**Comment by jethrokuan** [comment]
Was just trying out `forge`'s create PR from issue and it did weird stuff.

I'm not sure I like the proliferation of these "immediate" commands, if one only uses the immediate versions, the correct approach would be to change the template, adding `:immediate-finish t` to the default `org-roam-capture-template`.

**Comment by AlexanderDavid** [comment]
@jethrokuan The problem I find with `:immediate finish` is that it doesn't pop up in a buffer, it just adds it as a file.

**Comment by jethrokuan** [comment]
The addition of immediate finish (and having only 1 template) is the only thing that differentiates the normal and the immediate version of the commands, so once that is added they are functionally equivalent

**Comment by jmburgos** [comment]
But I do have a single template that includes `:immediate finish`, and if I use `org-roam-find-file` or `org-roam-insert` and type the name of a new note, I get the "Capture buffer" temporary buffer and I need to do C-c C-c to close it and keep writting.  

I do have a different template in orb-template, though. Would that make the difference?

**Comment by TimQuelch** [comment]
@jmburgos do you have it as `:immediate-finish t` in your template?

**Comment by jmburgos** [comment]
@TimQuelch Yes, I do. This is my template:

```
(org-roam-capture-templates '(
			      ("d" "default" plain #'org-roam--capture-get-point
			       :file-name "notes/${slug}"
			       :head "#+TITLE: ${title} \n#+CREATED: %U\n#+EDITED: %U\n#+ROAM_ALIAS: \n#+ROAM_TAGS: \n"
			       "%?"
			       :unnarrowed t
			       :immediate-finish t)
			      ))
```
As as said, I also have a different template in orb-templates, but that should not be an issue:

```
  (orb-templates
      '(("r" "ref" plain (function org-roam-capture--get-point) ""
         :file-name "refs/${citekey}"
         :head "#+TITLE: ${title}\n#+ROAM_KEY: ${ref}\n#+CREATED: %U\n#+EDITED: %U\n#+ROAM_TAGS: \n* Notes on cite:${citekey}\n :PROPERTIES:\n :Custom_ID:  ${citekey}\n :PDF: /home/julian/Documents/Refs/${citekey}.pdf\n :END:\n%? "
        :unnarrowed t
        :immediate-finish t)))
```

**Comment by jethrokuan** [comment]
@jmburgos you have an error in your template. the argument `"%?"` is positional, while the rest are key-value pairs. The positional argument must come first.

```
(setq org-roam-capture-templates '(
			      ("d" "default" plain #'org-roam--capture-get-point
                    "%?"
			       :file-name "notes/${slug}"
			       :head "#+TITLE: ${title} \n#+CREATED: %U\n#+EDITED: %U\n#+ROAM_ALIAS: \n#+ROAM_TAGS: \n"
			       :unnarrowed t
                   :immediate-finish t
			       )
			      ))```

**Comment by jmburgos** [comment]
Wow! I have not noticed that.  I guess Emacs teaches us that even the small things matter.  With the correct template things work as they should, and we do not really need the "immediate" functions.  Thanks!  I am getting closer to note taking nirvana....

**Pull request merged**
