### PR TITLE
(feat)capture: support template in OLP nodes.

### PR DESCRIPTION
**Pull request by bricewge**
###### Motivation for this change

I wanted to create weeklies capture as it was discussed in https://github.com/org-roam/org-roam/issues/1411#issuecomment-788238542 already but didn't manage to do it too.

Here is example:
``` elisp
(setq org-roam-dailies-capture-templates
      '(("d" "default" entry "** %?" :if-new
        (file+head+olp "%<%G-W%V>.org" "#+title: %<%G-W%V>\n"
                       ("%<%A %Y-%m-%d>")))))
```

### CODE REVIEW

**Comment by bricewge** [comment]
@jethrokuan gentle ping

Can I have a review on this PR?

**Comment by jethrokuan** [comment]
@bricewge thanks for the ping

The changes don't feel like they're in the right place. `org-roam-capture--fill-template` has always had this trailing newline issue, because `org-capture-fill-template` ensures there's a newline at the end of the template post-filling. The right approach would be to add an option to `org-roam-capture-fill-template` that allows for a no-newline version of template filling, since this is also used elsewhere.

**Comment by jethrokuan** [comment]
@bricewge template expansion in OLP is now supported by #2010 , hope that helps

**Comment by bricewge** [comment]
@jethrokuan Thank you for the fix! And sorry I didn't managed to adjust my PR in time.

**Pull request closed without merging**
