### PR TITLE
Update org-roam-mode.el

### PR DESCRIPTION
**Pull request by alaiyeshi025**
Modifiy preview related logic

### CODE REVIEW

**Comment by jethrokuan** [comment]
It's not clear to me why this logic is an improvement over the current one. E.g. when I say parent element, it does not refer to the heading it is under. I would appreciate if you provided some screenshots on what changed and why.

**Comment by alaiyeshi025** [comment]
> It's not clear to me why this logic is an improvement over the current one. E.g. when I say parent element, it does not refer to the heading it is under. I would appreciate if you provided some screenshots on what changed and why.

Thanks for replying.
I modified the logic because I've found that current code generate the following result:


Not sure the original result is intended or a "bug", while I thought the following would be more convenient for me (as of a newbie to org-roam):


Again, thanks for your time and wonderful work!

**Comment by jethrokuan** [comment]
https://github.com/org-roam/org-roam/pull/1756 contains a change that pulls the outline into greyed preview, which should include your `sdfsadf` headline. Update to latest commit and rebuild your cache for these files and you should observe the change.

**Comment by alaiyeshi025** [comment]
> #1756 contains a change that pulls the outline into greyed preview, which should include your `sdfsadf` headline. Update to latest commit and rebuild your cache for these files and you should observe the change.

Great! Thanks a lot!

**Pull request closed without merging**
