### PR TITLE
(doc): Add async update to Getting Started

### PR DESCRIPTION
**Pull request by nobiot**
Clarification about the asycn db update seems helpful for beginners.

I tried my best to follow the writing style of the original. Please advise if this is appropriate.

###### Motivation for this change
Refer to this Slack thread
https://orgroam.slack.com/archives/CV160S8EL/p1608039505055000

### CODE REVIEW

**Comment by jethrokuan** [comment]
LGTM, this info is important to know for users.

**Comment by jcguu95** [comment]
Hello,

Wanting the async feature, I took a look into the code.. but it doesn't appear to me that there's any. Would you mind pointing me out the entry point?

In particular, in `org-roam-db.el`, there is no `async` method called. It seems to be using `emacsql` fundamentally, but afaik it doesn't support async method either as in [this issue](https://github.com/skeeto/emacsql/issues/59).

**Comment by jethrokuan** [comment]
I removed usage of `async`, because it's flaky and difficult to support. Updating on `idle-timer` is an alright alternative, and should be the default.

**Comment by jcguu95** [comment]
That's sad to hear.. as my roam folder has grown to a point while each `db-sync` could freeze emacs up to 10 seconds. Sometimes I'd just disable `roam` because it's not clear to me when it's going to `db-sync`. 

It's a separate issue, but can I turn off auto-sync completely, and call it manually when I need?

**Comment by jethrokuan** [comment]
> It's a separate issue, but can I turn off auto-sync completely, and call it manually when I need?

Not in v1, but will be made possible in v2.

**Pull request merged**
